darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: yolov4-tiny-myClasses.cfg
      weight_file:
        name: yolov4-tiny-myClasses_final.weights
      threshold:
        value: 0.3
      detection_classes:
        names:
          - person
          - stop
          - speed50
          - speed30
          - speedbump
